services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.13
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - dev
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:6.2.13
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
    volumes:
      - kafka_secrets:/etc/kafka/secrets
      - kafka_data:/var/lib/kafka/data
    networks:
      - dev
    depends_on:
      - zookeeper
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "kafka-topics", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s

  elasticsearch:
    image: elasticsearch:9.0.4
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      # Привязка конфига
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:rw
      - elasticsearch_data:/usr/share/elasticsearch/data:rw
    networks:
      - dev
    restart: unless-stopped
    # Ограничение памяти (опционально, но рекомендуется)
    mem_limit: 2g
    # Пользователь (если нужен, как в твоём случае: 1000:0)
    user: "1000:0"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
  redis:
    image: redis
    container_name: my-redis
    hostname: my-redis
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_:/data
    networks:
      - dev
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_:/var/lib/postgresql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
  

  productservice:
    build:
      context: ./ProductService
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      KAFKA_SERVER: ${KAFKA_SERVER}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}


    networks:
      - dev
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    restart: unless-stopped
    
  searchservice:
    build:
      context: ./SearchService
    environment:
      name_to_elastic: ${name_to_elastic}
      password_to_elastic: ${password_to_elastic}
      password_to_certificate: ${password_to_certificate}
      ELASTIC_HOST: ${ELASTIC_HOST}
      ELASTIC_PORT: ${ELASTIC_PORT}
      KAFKA_SERVER: ${KAFKA_SERVER}
    networks:
      - dev
    depends_on:
      kafka:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped

  commentsservice:
    build:
      context: ./CommentsService
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      KAFKA_SERVER: ${KAFKA_SERVER}

    networks:
      - dev
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    restart: unless-stopped
  
  buyservice:
    build:
      context: ./BuyService
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      KAFKA_SERVER: ${KAFKA_SERVER}
    networks:
      - dev
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    restart: unless-stopped

  userservice:
    build:
      context: ./UserService
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      

    networks:
      - dev
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
      
  frontend:
    build:
      context: ./Frontend
    depends_on:
      - userservice
      - buyservice
      - commentsservice
      - searchservice
      - productservice
    networks:
      - dev
    restart: unless-stopped


  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - frontend
    networks:
      - dev
      
  db-backup:
    build: ./backup
    environment:
      DB_HOST: postgres          
      DB_PORT: 5432
      DB_NAME: postgres          
      DB_USER: postgres
      PGPASSWORD: ${DB_PASSWORD}      
      GITHUB_TOKEN: ${GITHUB_TOKEN}       
    volumes:
      - backups:/backups         
    networks:
      - dev
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

networks:
  dev:

volumes:
  kafka_secrets:
  kafka_data:
  redis_:
  postgres_:
  elasticsearch_data:
  backups:
